version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '9000:9000'
    volumes:
      - ./volumes/wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:alpine
    volumes:
      - ./volumes/nginx:/etc/nginx/conf.d
      - ./volumes/wordpress_data:/var/www/html
    ports:
      - 8000:80
    links:
      - wordpress
  php:
    build: .
    volumes:
        - ./volumes/wordpress_data:/var/www/html
